# Generated by Django 5.0.3 on 2024-03-18 06:50

import django.db.models.deletion
import taelimodel.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=40, verbose_name='Enter Book Name')),
                ('bookdiscrib', models.CharField(max_length=1000, verbose_name='Discribe Book')),
                ('bookcover', models.ImageField(upload_to=taelimodel.models.uploadcover, verbose_name='Uploadbook Cover')),
                ('status', models.BooleanField(default=1, help_text='1-show,0-hide')),
                ('uploadedtime', models.DateTimeField(auto_now_add=True)),
                ('bookpageno', models.IntegerField(null=True, verbose_name='Enter book page')),
                ('bookprize', models.IntegerField(default=None, verbose_name='Enter the prize of the book')),
                ('bookno', models.IntegerField(default=None, editable=False, verbose_name='book no auto created')),
            ],
        ),
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryname', models.CharField(max_length=50, verbose_name='Enter Catagory Name')),
                ('showstatus', models.BooleanField(default=False, help_text='0-show,1-Hide', verbose_name='Status of The Book')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('booklang', models.CharField(default=None, max_length=10, verbose_name='book languageg u want')),
                ('bookpr', models.IntegerField(default=None)),
                ('orderstatus', models.BooleanField(default=0, help_text='0-payment not done,1-payment done')),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taelimodel.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='catgryname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='taelimodel.catagory', verbose_name='Select Catagory Name'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklang', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('German', 'German'), ('Italy', 'Italy'), ('French', 'French')], default=None, max_length=8, verbose_name='Enter The File Language')),
                ('bookpdf', models.FileField(upload_to=taelimodel.models.uploadbook, verbose_name='Upload In selected Language')),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taelimodel.books')),
            ],
            options={
                'unique_together': {('bookno', 'booklang')},
            },
        ),
    ]
