# Generated by Django 5.0.3 on 2024-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taelimodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookdiscrib_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Discribe Book'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookdiscrib_fr',
            field=models.CharField(max_length=1000, null=True, verbose_name='Discribe Book'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookdiscrib_nl',
            field=models.CharField(max_length=1000, null=True, verbose_name='Discribe Book'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookdiscrib_ta',
            field=models.CharField(max_length=1000, null=True, verbose_name='Discribe Book'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookname_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Enter Book Name'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookname_fr',
            field=models.CharField(max_length=40, null=True, verbose_name='Enter Book Name'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookname_nl',
            field=models.CharField(max_length=40, null=True, verbose_name='Enter Book Name'),
        ),
        migrations.AddField(
            model_name='books',
            name='bookname_ta',
            field=models.CharField(max_length=40, null=True, verbose_name='Enter Book Name'),
        ),
    ]
