# Generated by Django 5.0.6 on 2024-08-16 16:17

import django.db.models.deletion
import taelimodel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=taelimodel.models.uploadbook,
                        verbose_name="upload A Home Banner",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="adid",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="image",
            field=models.ImageField(
                default=None,
                upload_to=taelimodel.models.uploadcover,
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="name",
            field=models.CharField(
                default=None, max_length=20, verbose_name="Person Name"
            ),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation",
            field=models.CharField(default=None, max_length=20, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="booklang",
            field=models.CharField(
                default=None, max_length=10, verbose_name="Selected book languageg "
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="bookno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="taelimodel.books",
                verbose_name="Booke Number",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="ordertime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ordered Time"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ordered User",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="booklang",
            field=models.CharField(
                choices=[
                    ("Tamil", "Tamil"),
                    ("English", "English"),
                    ("German", "German"),
                    ("Italy", "Italy"),
                    ("French", "French"),
                ],
                default=None,
                max_length=8,
                verbose_name="File Language",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="bookpdf",
            field=models.FileField(
                upload_to=taelimodel.models.uploadbook,
                verbose_name="Book selected Language",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="cover",
            field=models.ImageField(
                default=None,
                upload_to=taelimodel.models.uploadcover,
                verbose_name="Project Cover",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="date",
            field=models.DateField(verbose_name="Project Date"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="file",
            field=models.FileField(
                default=None,
                upload_to=taelimodel.models.uploadbook,
                verbose_name="Project File",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="name",
            field=models.CharField(
                default=None, max_length=20, verbose_name="Project Name"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="prid",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
