# Generated by Django 5.0.6 on 2024-06-21 19:31

import taelimodel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0002_books_bookdiscrib_it_books_bookname_it_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminstration",
            fields=[
                ("name", models.CharField(default=False, max_length=20)),
                (
                    "image",
                    models.ImageField(
                        default=False, upload_to=taelimodel.models.uploadcover
                    ),
                ),
                ("adid", models.AutoField(primary_key=True, serialize=False)),
                ("ocation", models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=False, max_length=20)),
                ("date", models.DateField()),
                (
                    "cover",
                    models.ImageField(
                        default=False, upload_to=taelimodel.models.uploadcover
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default=False, upload_to=taelimodel.models.uploadbook
                    ),
                ),
            ],
        ),
    ]
