# Generated by Django 5.0.6 on 2024-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0002_banner_alter_adminstration_adid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
