# Generated by Django 5.0.3 on 2024-04-07 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0002_books_bookdiscrib_en_books_bookdiscrib_fr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="bookdiscrib_nl",
            new_name="bookdiscrib_de",
        ),
        migrations.RenameField(
            model_name="books",
            old_name="bookname_nl",
            new_name="bookname_de",
        ),
    ]
