# Generated by Django 5.0.6 on 2024-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0003_banner_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Paid Book or"),
        ),
    ]
