# Generated by Django 5.0.3 on 2024-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0003_rename_bookdiscrib_nl_books_bookdiscrib_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="catagoryname_de",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Enter Catagory Name"
            ),
        ),
        migrations.AddField(
            model_name="catagory",
            name="catagoryname_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Enter Catagory Name"
            ),
        ),
        migrations.AddField(
            model_name="catagory",
            name="catagoryname_fr",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Enter Catagory Name"
            ),
        ),
        migrations.AddField(
            model_name="catagory",
            name="catagoryname_ta",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Enter Catagory Name"
            ),
        ),
    ]
