# Generated by Django 5.0.6 on 2024-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0004_language_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="paid",
        ),
        migrations.AddField(
            model_name="books",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Paid Book or"),
        ),
    ]
