# Generated by Django 5.0.6 on 2024-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0005_remove_language_paid_books_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="paid",
            field=models.BooleanField(default=True, verbose_name="Paid Book or"),
        ),
    ]
