# Generated by Django 5.0.6 on 2024-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0006_alter_books_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="quote",
            field=models.CharField(blank=True, max_length=40, verbose_name="quote"),
        ),
        migrations.AlterField(
            model_name="books",
            name="paid",
            field=models.BooleanField(default=True, verbose_name="book paid"),
        ),
    ]
