# Generated by Django 5.0.6 on 2024-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0007_banner_quote_alter_books_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="bookdiscrib_si",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Discribe Book"
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="bookname_si",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Enter Book Name"
            ),
        ),
        migrations.AddField(
            model_name="catagory",
            name="catagoryname_si",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Enter Catagory Name"
            ),
        ),
    ]
