# Generated by Django 5.0 on 2024-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0008_books_bookdiscrib_si_books_bookname_si_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminstration",
            name="name",
            field=models.CharField(
                default=None, max_length=30, verbose_name="Person Name"
            ),
        ),
    ]
