# Generated by Django 5.0 on 2024-08-18 15:44

import taelimodel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0009_alter_adminstration_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote",
                    models.CharField(default=None, max_length=60, verbose_name="Quote"),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Oursponser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default=None,
                        upload_to=taelimodel.models.uploadbook,
                        verbose_name="Sponser'd Logo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None, max_length=20, verbose_name="Sponsord Name"
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
