# Generated by Django 5.0 on 2024-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0011_remove_banner_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerquote",
            name="date_de",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="date_en",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="date_fr",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="date_it",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="date_si",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="date_ta",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_de",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_en",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_fr",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_it",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_si",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="quote_ta",
            field=models.CharField(
                default=None, max_length=60, null=True, verbose_name="Quote"
            ),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_de",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_en",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_fr",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_it",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_si",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bannerquote",
            name="status_ta",
            field=models.BooleanField(default=True),
        ),
    ]
