# Generated by Django 5.0 on 2024-08-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0013_remove_bannerquote_date_de_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminstration",
            options={
                "verbose_name": "Our Adminastraion",
                "verbose_name_plural": "Our Adminastraion",
            },
        ),
        migrations.AlterModelOptions(
            name="banner",
            options={
                "verbose_name": "Home Banner",
                "verbose_name_plural": "Home Banner",
            },
        ),
        migrations.AlterModelOptions(
            name="bannerquote",
            options={
                "verbose_name": "Banner Quote",
                "verbose_name_plural": "Banner Quote",
            },
        ),
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "Books ", "verbose_name_plural": "Books"},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={
                "verbose_name": "Book Order In Cart",
                "verbose_name_plural": "Book Order In Cart",
            },
        ),
        migrations.AlterModelOptions(
            name="catagory",
            options={
                "verbose_name": "Books Catagory",
                "verbose_name_plural": "Books Catagory",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "verbose_name": "Books In Languages",
                "verbose_name_plural": "Books In Languages",
            },
        ),
        migrations.AlterModelOptions(
            name="oursponser",
            options={
                "verbose_name": "Our Sponser",
                "verbose_name_plural": "Our Sponser",
            },
        ),
        migrations.AlterModelOptions(
            name="projects",
            options={
                "verbose_name": "Our Projects",
                "verbose_name_plural": "Our Projects",
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="catagory",
            name="showstatus",
            field=models.BooleanField(
                default=False, help_text="0-show,1-Hide", verbose_name="Hide"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="bookno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="taelimodel.books",
                verbose_name="Book Number",
            ),
        ),
    ]
