# Generated by Django 5.0 on 2024-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taelimodel",
            "0014_alter_adminstration_options_alter_banner_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adminstration",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
