# Generated by Django 5.0 on 2024-08-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0015_adminstration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminstration",
            name="ocation_de",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
        migrations.AddField(
            model_name="adminstration",
            name="ocation_en",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
        migrations.AddField(
            model_name="adminstration",
            name="ocation_fr",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
        migrations.AddField(
            model_name="adminstration",
            name="ocation_it",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
        migrations.AddField(
            model_name="adminstration",
            name="ocation_si",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
        migrations.AddField(
            model_name="adminstration",
            name="ocation_ta",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="Ocation"
            ),
        ),
    ]
