# Generated by Django 5.0 on 2024-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taelimodel",
            "0016_adminstration_ocation_de_adminstration_ocation_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminstration",
            name="ocation",
            field=models.CharField(max_length=20, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_de",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_en",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_fr",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_it",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_si",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
        migrations.AlterField(
            model_name="adminstration",
            name="ocation_ta",
            field=models.CharField(max_length=20, null=True, verbose_name="Ocation"),
        ),
    ]
