# Generated by Django 5.0 on 2024-10-31 12:51

import taelimodel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0018_projects_gbid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impresm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=taelimodel.models.uploadimprsm,
                        verbose_name="upload daetail file",
                    ),
                ),
                ("update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
