# Generated by Django 5.0 on 2024-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taelimodel", "0019_impresm"),
    ]

    operations = [
        migrations.AddField(
            model_name="impresm",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
