# Generated by Django 4.2.11 on 2024-10-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taelimodel', '0020_impresm_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impresm',
            options={'get_latest_by': 'update'},
        ),
    ]
